/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flow3;

import javax.swing.DefaultListModel;

/**
 *
 * @author Andreas & Emil
 */
public class Gui extends javax.swing.JFrame
{

    /**
     * Creates new form Gui
     */
    QuizzControlIF control = new Control();
    DefaultListModel model1;
    
    public Gui()
    {
        initComponents();
        model1 = new DefaultListModel();
        jList1.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jQuestion = new javax.swing.JTextField();
        jAnswer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        saveWordsButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jSelectGame = new javax.swing.JButton();
        jTextGame = new javax.swing.JTextField();
        jAddGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelcounter = new javax.swing.JLabel();
        statusjLabel = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Question:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 79, -1, -1));

        jLabel2.setText("Answer:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 124, -1, 20));

        jQuestion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(jQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 76, 175, -1));
        jPanel1.add(jAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 124, 175, -1));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 68, 74, 36));

        jButton2.setText("Guess");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 115, 74, 39));

        jButton4.setText("Look up");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 172, 74, 34));

        saveWordsButton.setText("Save to txt");
        saveWordsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveWordsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveWordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 281, 147, 46));

        jButton5.setText("Add new question");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 281, 151, 46));

        jButton3.setText("Load from txt");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 346, 147, 45));

        jButton6.setText("Delete question");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 347, 151, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Too hard? Look it up!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 175, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 71, 149, 150));

        jSelectGame.setText("Select Game");
        jSelectGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jSelectGameActionPerformed(evt);
            }
        });
        jPanel1.add(jSelectGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 239, 149, 36));
        jPanel1.add(jTextGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, 149, 32));

        jAddGame.setText("Add new game category");
        jAddGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jAddGameActionPerformed(evt);
            }
        });
        jPanel1.add(jAddGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 345, -1, 47));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Title of game");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 40));

        jLabel4.setText("Question counter:");

        jLabelcounter.setText("    ");
        jLabelcounter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        statusjLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelcounter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcounter))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jAddGameActionPerformed
    {//GEN-HEADEREND:event_jAddGameActionPerformed
        String Cname = jTextGame.getText();
        model1.addElement(Cname);
        control.addGame(Cname);
        control.selectGame(Cname);
        jLabel6.setText(control.getSelectedGameName());
        statusjLabel.setText("New category has been saved!");
    }//GEN-LAST:event_jAddGameActionPerformed
    
    private void jSelectGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jSelectGameActionPerformed
    {//GEN-HEADEREND:event_jSelectGameActionPerformed
        String tmp = (String) jList1.getSelectedValue();
        control.selectGame(tmp);
        String gamename = control.getSelectedGameName();
        if (gamename == null)
        {
            jLabel6.setText("Game not found!");
        } else
        {
            jLabel6.setText(gamename);
        }
        
    }//GEN-LAST:event_jSelectGameActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        control.delete(jQuestion.getText());
        control.delete(jAnswer.getText());
//        jLabelcounter.setText("" + control.size());
        statusjLabel.setText("Question has been deleted");
        jQuestion.setText("");
        jAnswer.setText("");
        
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        model1.clear();
        control.clear();
        control.load();
        
        statusjLabel.setText("Questions from textfile has been loaded");
        jLabelcounter.setText("0");
//        model1.addElement(control.getGameNames().toString());
        String[] midlertidig = control.getGameNames();
        for (int i = 0; i < midlertidig.length; i++)
        {
            model1.addElement(midlertidig[i]);
        }

        //Remember to make sure questions are only loaded once
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        
        String question = jQuestion.getText();
        String answer = jAnswer.getText();
        control.add(question, answer);
        statusjLabel.setText("Words has been added");
//        jLabelcounter.setText("" + control.size());

    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void saveWordsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveWordsButtonActionPerformed
    {//GEN-HEADEREND:event_saveWordsButtonActionPerformed
        Boolean save = control.save();
//        jLabelcounter.setText("" + control.size());
        if (save)
        {
            statusjLabel.setText("Words has been saved");
        } else
        {
            statusjLabel.setText("Words has not been saved");
        }
    }//GEN-LAST:event_saveWordsButtonActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        String question = jQuestion.getText();
        String answer = control.lookup(question);
        jAnswer.setText(answer);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        String question = jQuestion.getText();
        String answer = jAnswer.getText();
        
        if (control.checkGuess(question, answer))
        {
            statusjLabel.setText("Correct!");
//            jLabelcounter.setText("" + control.size());
        } else
        {
            statusjLabel.setText("Wrong. Try agian");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        
        String word = control.getRandomQuestion();
        jQuestion.setText(word);
        jAnswer.setText("");
//        jLabelcounter.setText("" + control.size());
        if (jQuestion.getText().equals(""))
        {
            statusjLabel.setText("There are no more wordpairs");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jQuestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jQuestionActionPerformed
    {//GEN-HEADEREND:event_jQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddGame;
    private javax.swing.JTextField jAnswer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelcounter;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQuestion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSelectGame;
    private javax.swing.JTextField jTextGame;
    private javax.swing.JButton saveWordsButton;
    private javax.swing.JLabel statusjLabel;
    // End of variables declaration//GEN-END:variables
}
